name: Review application

on:
  issues:
    types: [opened, edited]

jobs:
  review-application:
    runs-on: ubuntu-latest
    if: vars.PROCESSOR_ENABLED == 'true' && contains(github.event.issue.labels.*.name, 'application')
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Fetch processor
        uses: dsaltares/fetch-gh-release-asset@a40c8b4a0471f9ab81bdf73a010f74cc51476ad4 # 1.1.1
        with:
          file: "processor"
          target: "./processor"

      - name: Automated application review
        run: |
          chmod +x ./processor
          ./processor review
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          OP_BOT_PAT: ${{ secrets.OP_BOT_PAT }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
